# Generated by Django 3.1.4 on 2021-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_score', models.FloatField()),
                ('university_rating', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('research', models.FloatField()),
            ],
        ),
    ]
