# Generated by Django 3.1.4 on 2021-02-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredResults',
            new_name='PredResult',
        ),
    ]
