# Generated by Django 3.1.4 on 2021-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0002_auto_20210205_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresult',
            name='classification',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
