# Generated by Django 3.1.4 on 2021-02-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_predresult_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresult',
            name='classification',
        ),
    ]
