# Generated by Django 3.1.4 on 2021-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0004_remove_predresult_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresult',
            name='research',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predresult',
            name='university_rating',
            field=models.IntegerField(),
        ),
    ]
