# Generated by Django 3.1.4 on 2021-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0005_auto_20210206_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresult',
            name='gre_score',
            field=models.IntegerField(),
        ),
    ]
