# Generated by Django 3.1.4 on 2021-02-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0006_auto_20210206_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredResult',
        ),
    ]
